<?php

$routes->group('fmis', ['namespace' => 'Fmis\Controllers'], static function ($routes) {
	$routes->get('', 'HomeController::index'); 
	$routes->get('set-year', 'HomeController::selectYear'); 
	$routes->post('set-year', 'HomeController::setYear'); 
	$routes->get('farmer', 'FarmerController::index'); 
	$routes->get('farmer/new', 'FarmerController::newItem'); 
	$routes->get('farmer/(:num)', 'FarmerController::showItem/$1', ['filter' => 'restrict-farm']);
	$routes->get('farmer/pending', 'FarmerController::showPendingDir');
	$routes->get('farmer/add-from-json', 'FarmerController::addJson');
	$routes->post('farmer/add-from-json', 'FarmerController::importFromJson');
	$routes->get('farmer/add-po', 'FarmerController::newPo');
	$routes->get('farmer/show-po', 'FarmerController::showPo');
	$routes->post('farmer/add-po', 'FarmerController::savePo');
	$routes->post('farmer/remove-po', 'FarmerController::removePo');
	$routes->post('farmer/delete', 'FarmerController::delete');
	$routes->get('farmer-user/link', 'UserFarmerController::index');
	$routes->post('farmer-user/link', 'UserFarmerController::linkUserToFarmer');
	$routes->get('parcel/(:num)', 'ParcelController::showItem/$1', ['filter' => 'restrict-parcel']);
	$routes->get('fertiliser', 'FertiliserController::index', ['filter' => 'restrict-param']); 
	$routes->get('fertiliser/new', 'FertiliserController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('fertiliser', 'FertiliserController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('fertiliser/(:num)', 'FertiliserController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('fertiliser/delete', 'FertiliserController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('unit-measurement', 'UnitMeasurementController::index', ['filter' => 'restrict-param']); 
	$routes->get('unit-measurement/new', 'UnitMeasurementController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('unit-measurement', 'UnitMeasurementController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('unit-measurement/(:num)', 'UnitMeasurementController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('unit-measurement/delete', 'UnitMeasurementController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('fertiliser-application', 'FertiliserApplicationController::index', ['filter' => 'restrict-param']); 
	$routes->get('fertiliser-application/new', 'FertiliserApplicationController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('fertiliser-application', 'FertiliserApplicationController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('fertiliser-application/(:num)', 'FertiliserApplicationController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('fertiliser-application/delete', 'FertiliserApplicationController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('farming-stage', 'FarmingStageController::index', ['filter' => 'restrict-param']); 
	$routes->get('farming-stage/new', 'FarmingStageController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('farming-stage', 'FarmingStageController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('farming-stage/(:num)', 'FarmingStageController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('farming-stage/delete', 'FarmingStageController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('fertilise-equipment', 'FertiliseEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('fertilise-equipment/new', 'FertiliseEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('fertilise-equipment', 'FertiliseEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('fertilise-equipment/(:num)', 'FertiliseEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('fertilise-equipment/delete', 'FertiliseEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('specialised-fertiliser', 'SpecialisedFertiliserController::index', ['filter' => 'restrict-param']); 
	$routes->get('specialised-fertiliser/new', 'SpecialisedFertiliserController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('specialised-fertiliser', 'SpecialisedFertiliserController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('specialised-fertiliser/(:num)', 'SpecialisedFertiliserController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('specialised-fertiliser/delete', 'SpecialisedFertiliserController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('fertilisation', 'FertilisationController::index'); 
	$routes->get('fertilisation/new', 'FertilisationController::newItem'); 
	$routes->post('fertilisation', 'FertilisationController::saveItem'); 
	$routes->get('fertilisation/(:num)', 'FertilisationController::showItem/$1'); 
	$routes->post('fertilisation/delete', 'FertilisationController::deleteItem'); 
	$routes->get('fertilisation-from-parcel/(:num)', 'FertilisationController::createDirectiveFromParcel/$1'); 
	$routes->get('fertilisation-parcel', 'FertilisationParcelController::index'); 
	$routes->get('fertilisation-parcel/new', 'FertilisationParcelController::newItem'); 
	$routes->post('fertilisation-parcel', 'FertilisationParcelController::saveItem'); 
	$routes->get('fertilisation-parcel/(:num)', 'FertilisationParcelController::showItem/$1'); 
	$routes->post('fertilisation-parcel/delete', 'FertilisationParcelController::deleteItem'); 
	$routes->post('fertilisation-bulk', 'FertilisationBulkController::saveItem'); 
	$routes->get('fertilisation-bulk/(:num)', 'FertilisationBulkController::showItem/$1'); 
	$routes->get('fertilisation-bulk-new', 'FertilisationBulkController::newItem'); 
	$routes->post('fertilisation-bulk-new', 'FertilisationBulkController::saveBulk'); 
	$routes->get('fertilisation-global-new', 'FertilisationBulkController::newGlobalItem'); 
	$routes->post('fertilisation-global-new', 'FertilisationBulkController::saveGlobal'); 
	$routes->get('trap', 'TrapController::index', ['filter' => 'restrict-param']); 
	$routes->get('trap/new', 'TrapController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('trap', 'TrapController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('trap/(:num)', 'TrapController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('trap/delete', 'TrapController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('mass-trapping', 'MassTrappingController::index'); 
	$routes->get('mass-trapping-from-parcel/(:num)', 'MassTrappingController::createDirectiveFromParcel/$1');
	$routes->get('mass-trapping/new', 'MassTrappingController::newItem'); 
	$routes->post('mass-trapping', 'MassTrappingController::saveItem'); 
	$routes->get('mass-trapping/(:num)', 'MassTrappingController::showItem/$1'); 
	$routes->post('mass-trapping/delete', 'MassTrappingController::deleteItem'); 
	$routes->get('mass-trapping-parcel', 'MassTrappingParcelController::index'); 
	$routes->get('mass-trapping-parcel/new', 'MassTrappingParcelController::newItem'); 
	$routes->post('mass-trapping-parcel', 'MassTrappingParcelController::saveItem'); 
	$routes->get('mass-trapping-parcel/(:num)', 'MassTrappingParcelController::showItem/$1'); 
	$routes->post('mass-trapping-parcel/delete', 'MassTrappingParcelController::deleteItem'); 
	$routes->post('mass-trapping-bulk', 'MassTrappingBulkController::saveItem'); 
	$routes->get('mass-trapping-bulk/(:num)', 'MassTrappingBulkController::showItem/$1'); 
	$routes->get('mass-trapping-bulk-new', 'MassTrappingBulkController::newItem'); 
	$routes->post('mass-trapping-bulk-new', 'MassTrappingBulkController::saveBulk'); 
	$routes->get('mass-trapping-global-new', 'MassTrappingBulkController::newGlobalItem'); 
	$routes->post('mass-trapping-global-new', 'MassTrappingBulkController::saveGlobal'); 
	$routes->get('protective-product', 'ProtectiveProductController::index', ['filter' => 'restrict-param']); 
	$routes->get('protective-product/new', 'ProtectiveProductController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('protective-product', 'ProtectiveProductController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('protective-product/(:num)', 'ProtectiveProductController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('protective-product/delete', 'ProtectiveProductController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('product-active/new', 'ProductActiveController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('product-active', 'ProductActiveController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('product-active/(:num)', 'ProductActiveController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('product-active/delete', 'ProductActiveController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('spray-equipment', 'SprayEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('spray-equipment/new', 'SprayEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('spray-equipment', 'SprayEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('spray-equipment/(:num)', 'SprayEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('spray-equipment/delete', 'SprayEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('spray', 'SprayController::index'); 
	$routes->get('spray-from-parcel/(:num)', 'SprayController::createDirectiveFromParcel/$1');
	$routes->get('spray/new', 'SprayController::newItem'); 
	$routes->post('spray', 'SprayController::saveItem'); 
	$routes->get('spray/(:num)', 'SprayController::showItem/$1'); 
	$routes->post('spray/delete', 'SprayController::deleteItem'); 
	$routes->get('spray-parcel', 'SprayParcelController::index'); 
	$routes->get('spray-parcel/new', 'SprayParcelController::newItem'); 
	$routes->post('spray-parcel', 'SprayParcelController::saveItem'); 
	$routes->get('spray-parcel/(:num)', 'SprayParcelController::showItem/$1'); 
	$routes->post('spray-parcel/delete', 'SprayParcelController::deleteItem'); 
	$routes->post('spray-bulk', 'SprayBulkController::saveItem'); 
	$routes->get('spray-bulk/(:num)', 'SprayBulkController::showItem/$1'); 
	$routes->get('spray-bulk-new', 'SprayBulkController::newItem'); 
	$routes->post('spray-bulk-new', 'SprayBulkController::saveBulk'); 
	$routes->get('spray-global-new', 'SprayBulkController::newGlobalItem'); 
	$routes->post('spray-global-new', 'SprayBulkController::saveGlobal'); 
	$routes->get('pruning-type', 'PruningTypeController::index', ['filter' => 'restrict-param']); 
	$routes->get('pruning-type/new', 'PruningTypeController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('pruning-type', 'PruningTypeController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('pruning-type/(:num)', 'PruningTypeController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('pruning-type/delete', 'PruningTypeController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('pruning-equipment', 'PruningEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('pruning-equipment/new', 'PruningEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('pruning-equipment', 'PruningEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('pruning-equipment/(:num)', 'PruningEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('pruning-equipment/delete', 'PruningEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('pruning', 'PruningController::index'); 
	$routes->get('pruning-from-parcel/(:num)', 'PruningController::createDirectiveFromParcel/$1');
	$routes->get('pruning/new', 'PruningController::newItem'); 
	$routes->post('pruning', 'PruningController::saveItem'); 
	$routes->get('pruning/(:num)', 'PruningController::showItem/$1'); 
	$routes->post('pruning/delete', 'PruningController::deleteItem'); 
	$routes->get('pruning-parcel', 'PruningParcelController::index'); 
	$routes->get('pruning-parcel/new', 'PruningParcelController::newItem'); 
	$routes->post('pruning-parcel', 'PruningParcelController::saveItem'); 
	$routes->get('pruning-parcel/(:num)', 'PruningParcelController::showItem/$1'); 
	$routes->post('pruning-parcel/delete', 'PruningParcelController::deleteItem'); 
	$routes->post('pruning-bulk', 'PruningBulkController::saveItem'); 
	$routes->get('pruning-bulk/(:num)', 'PruningBulkController::showItem/$1'); 
	$routes->get('pruning-bulk-new', 'PruningBulkController::newItem'); 
	$routes->post('pruning-bulk-new', 'PruningBulkController::saveBulk'); 
	$routes->get('pruning-global-new', 'PruningBulkController::newGlobalItem'); 
	$routes->post('pruning-global-new', 'PruningBulkController::saveGlobal'); 
	$routes->get('work-type', 'WorkTypeController::index', ['filter' => 'restrict-param']); 
	$routes->get('work-type/new', 'WorkTypeController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('work-type', 'WorkTypeController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('work-type/(:num)', 'WorkTypeController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('work-type/delete', 'WorkTypeController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('plant-species-sow', 'PlantSpeciesSowController::index', ['filter' => 'restrict-param']); 
	$routes->get('plant-species-sow/new', 'PlantSpeciesSowController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('plant-species-sow', 'PlantSpeciesSowController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('plant-species-sow/(:num)', 'PlantSpeciesSowController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('plant-species-sow/delete', 'PlantSpeciesSowController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('cover-crop-species', 'CoverCropSpeciesController::index', ['filter' => 'restrict-param']); 
	$routes->get('cover-crop-species/new', 'CoverCropSpeciesController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('cover-crop-species', 'CoverCropSpeciesController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('cover-crop-species/(:num)', 'CoverCropSpeciesController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('cover-crop-species/delete', 'CoverCropSpeciesController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('plough-equipment', 'PloughEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('plough-equipment/new', 'PloughEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('plough-equipment', 'PloughEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('plough-equipment/(:num)', 'PloughEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('plough-equipment/delete', 'PloughEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('soil-management', 'SoilManagementController::index'); 
	$routes->get('soil-management-from-parcel/(:num)', 'SoilManagementController::createDirectiveFromParcel/$1');
	$routes->get('soil-management/new', 'SoilManagementController::newItem'); 
	$routes->post('soil-management', 'SoilManagementController::saveItem'); 
	$routes->get('soil-management/(:num)', 'SoilManagementController::showItem/$1'); 
	$routes->post('soil-management/delete', 'SoilManagementController::deleteItem'); 
	$routes->get('soil-management-parcel', 'SoilManagementParcelController::index'); 
	$routes->get('soil-management-parcel/new', 'SoilManagementParcelController::newItem'); 
	$routes->post('soil-management-parcel', 'SoilManagementParcelController::saveItem'); 
	$routes->get('soil-management-parcel/(:num)', 'SoilManagementParcelController::showItem/$1'); 
	$routes->post('soil-management-parcel/delete', 'SoilManagementParcelController::deleteItem'); 
	$routes->post('soil-management-bulk', 'SoilManagementBulkController::saveItem'); 
	$routes->get('soil-management-bulk/(:num)', 'SoilManagementBulkController::showItem/$1'); 
	$routes->get('soil-management-bulk-new', 'SoilManagementBulkController::newItem'); 
	$routes->post('soil-management-bulk-new', 'SoilManagementBulkController::saveBulk'); 
	$routes->get('soil-management-global-new', 'SoilManagementBulkController::newGlobalItem'); 
	$routes->post('soil-management-global-new', 'SoilManagementBulkController::saveGlobal'); 
	$routes->get('irrigation-equipment', 'IrrigationEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('irrigation-equipment/new', 'IrrigationEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('irrigation-equipment', 'IrrigationEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('irrigation-equipment/(:num)', 'IrrigationEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('irrigation-equipment/delete', 'IrrigationEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('irrigation', 'IrrigationController::index'); 
	$routes->get('irrigation-from-parcel/(:num)', 'IrrigationController::createDirectiveFromParcel/$1');
	$routes->get('irrigation/new', 'IrrigationController::newItem'); 
	$routes->post('irrigation', 'IrrigationController::saveItem'); 
	$routes->get('irrigation/(:num)', 'IrrigationController::showItem/$1'); 
	$routes->post('irrigation/delete', 'IrrigationController::deleteItem'); 
	$routes->get('irrigation-parcel', 'IrrigationParcelController::index'); 
	$routes->get('irrigation-parcel/new', 'IrrigationParcelController::newItem'); 
	$routes->post('irrigation-parcel', 'IrrigationParcelController::saveItem'); 
	$routes->get('irrigation-parcel/(:num)', 'IrrigationParcelController::showItem/$1'); 
	$routes->post('irrigation-parcel/delete', 'IrrigationParcelController::deleteItem'); 
	$routes->post('irrigation-bulk', 'IrrigationBulkController::saveItem'); 
	$routes->get('irrigation-bulk/(:num)', 'IrrigationBulkController::showItem/$1'); 
	$routes->get('irrigation-bulk-new', 'IrrigationBulkController::newItem'); 
	$routes->post('irrigation-bulk-new', 'IrrigationBulkController::saveBulk'); 
	$routes->get('irrigation-global-new', 'IrrigationBulkController::newGlobalItem'); 
	$routes->post('irrigation-global-new', 'IrrigationBulkController::saveGlobal'); 
	$routes->get('harvest-equipment', 'HarvestEquipmentController::index', ['filter' => 'restrict-param']); 
	$routes->get('harvest-equipment/new', 'HarvestEquipmentController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('harvest-equipment', 'HarvestEquipmentController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('harvest-equipment/(:num)', 'HarvestEquipmentController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('harvest-equipment/delete', 'HarvestEquipmentController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('harvesting', 'HarvestingController::index'); 
	$routes->get('harvesting-from-parcel/(:num)', 'HarvestingController::createDirectiveFromParcel/$1');
	$routes->get('harvesting/new', 'HarvestingController::newItem'); 
	$routes->post('harvesting', 'HarvestingController::saveItem'); 
	$routes->get('harvesting/(:num)', 'HarvestingController::showItem/$1'); 
	$routes->post('harvesting/delete', 'HarvestingController::deleteItem'); 
	$routes->get('harvest-parcel', 'HarvestParcelController::index'); 
	$routes->get('harvest-parcel/new', 'HarvestParcelController::newItem'); 
	$routes->post('harvest-parcel', 'HarvestParcelController::saveItem'); 
	$routes->get('harvest-parcel/(:num)', 'HarvestParcelController::showItem/$1'); 
	$routes->post('harvest-parcel/delete', 'HarvestParcelController::deleteItem'); 
	$routes->get('active-substance', 'ActiveSubstanceController::index', ['filter' => 'restrict-param']); 
	$routes->get('active-substance/new', 'ActiveSubstanceController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('active-substance', 'ActiveSubstanceController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('active-substance/(:num)', 'ActiveSubstanceController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('active-substance/delete', 'ActiveSubstanceController::deleteItem', ['filter' => 'restrict-param']); 
	$routes->get('parcel-soil', 'ParcelSoilController::index'); 
	$routes->get('parcel-soil/new', 'ParcelSoilController::newItem'); 
	$routes->post('parcel-soil', 'ParcelSoilController::saveItem'); 
	$routes->get('parcel-soil/(:num)', 'ParcelSoilController::showItem/$1'); 
	$routes->post('parcel-soil/delete', 'ParcelSoilController::deleteItem'); 
	$routes->get('parcel-leaf', 'ParcelLeafController::index'); 
	$routes->get('parcel-leaf/new', 'ParcelLeafController::newItem'); 
	$routes->post('parcel-leaf', 'ParcelLeafController::saveItem'); 
	$routes->get('parcel-leaf/(:num)', 'ParcelLeafController::showItem/$1'); 
	$routes->post('parcel-leaf/delete', 'ParcelLeafController::deleteItem'); 
	$routes->get('spd', 'SpdController::index'); 
	$routes->post('spd', 'SpdController::showItem'); 
	$routes->get('farm-inputs', 'FarmInputsController::index'); 
	$routes->get('farm-inputs/fertilisers', 'FarmInputsController::listFertilisers'); 
	$routes->get('farm-inputs/ppp', 'FarmInputsController::listPpp'); 
	$routes->get('farm-inputs/new', 'FarmInputsController::newItem'); 
	$routes->post('farm-inputs', 'FarmInputsController::saveItem'); 
	$routes->get('farm-inputs/(:num)', 'FarmInputsController::showItem/$1'); 
	$routes->post('farm-inputs/delete', 'FarmInputsController::deleteItem'); 
	$routes->get('farm-outputs', 'FarmOutputsController::index'); 
	$routes->get('farm-outputs/new', 'FarmOutputsController::newItem'); 
	$routes->post('farm-outputs', 'FarmOutputsController::saveItem'); 
	$routes->get('farm-outputs/(:num)', 'FarmOutputsController::showItem/$1'); 
	$routes->post('farm-outputs/delete', 'FarmOutputsController::deleteItem'); 
	$routes->get('farm-input-output', 'FarmInputOutputController::index');
	$routes->get('farm-input-output/download', 'FarmInputOutputController::downloadPdf');	
	$routes->get('supplier', 'SupplierController::index'); 
	$routes->get('supplier/new', 'SupplierController::newItem'); 
	$routes->post('supplier', 'SupplierController::saveItem'); 
	$routes->get('supplier/(:num)', 'SupplierController::showItem/$1'); 
	$routes->post('supplier/delete', 'SupplierController::deleteItem'); 
	$routes->get('buyer', 'BuyerController::index'); 
	$routes->get('buyer/new', 'BuyerController::newItem'); 
	$routes->post('buyer', 'BuyerController::saveItem'); 
	$routes->get('buyer/(:num)', 'BuyerController::showItem/$1'); 
	$routes->post('buyer/delete', 'BuyerController::deleteItem');
	$routes->post('get-cultivar-codes', 'ParamSoController::getCultivarCodes', ['filter' => 'restrict-param']); 
	$routes->get('photo', 'ParcelController::getPhoto');
	$routes->get('advisor', 'AdvisorController::index');
	$routes->get('advisor/new', 'AdvisorController::newItem');
	$routes->get('advisor/(:num)', 'AdvisorController::showItem/$1');
	$routes->post('advisor', 'AdvisorController::saveItem');
	$routes->get('po', 'PoController::index', ['filter' => 'restrict-param']); 
	$routes->get('po/new', 'PoController::newItem', ['filter' => 'restrict-param']); 
	$routes->post('po', 'PoController::saveItem', ['filter' => 'restrict-param']); 
	$routes->get('po/(:num)', 'PoController::showItem/$1', ['filter' => 'restrict-param']); 
	$routes->post('po/delete', 'PoController::deleteItem', ['filter' => 'restrict-param']); 
	
	$routes->get('openid-connect', 'OpenIDController::index');
});
	